name: coffee_talk_companion_app
description: A companion app for Coffee Talk, featuring character details, drink recipes, and a brewing simulation.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # State management
  lottie: ^3.2.0 # For animations (e.g., splash screen)
  http: 1.3.0 # For API calls or loading mock data
  flutter_svg: ^2.0.7 # For SVG image support
  intl: ^0.20.1 # For date/time formatting or localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/data/mock_data.json
    - lib/assets/images/ # Directory for images (logo, character images, etc.)

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
