name: coffee_talk_companion_app
description: A companion app for Coffee Talk, featuring character details, drink recipes, and a brewing simulation.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # State management
  lottie: ^3.2.0 # For animations (e.g., splash screen)
  http: 1.3.0 # For API calls or loading mock data
  flutter_svg: ^2.0.7 # For SVG image support
  intl: ^0.20.1 # For date/time formatting or localization
  carousel_slider: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/data/mock_data.json
    - lib/assets/images/ICON-FREYA.webp
    - lib/assets/images/ICON-LUA-01.webp
    - lib/assets/images/ICON-BAILEYS.webp
    - lib/assets/images/ICON-JORJI-01.webp
    - lib/assets/images/ICON-GALA.webp
    - lib/assets/images/ICON-HYDE.webp
    - lib/assets/images/ICON-MYRTILE-01.webp
    - lib/assets/images/ICON-RACHEL.webp
    - lib/assets/images/ICON-AQUA-01.webp
    - lib/assets/images/ICON-NEIL-01.webp
    - lib/assets/images/ICON-HENDRY-01.webp
    - lib/assets/images/Espresso.webp
    - lib/assets/images/STMJ.webp
    - lib/assets/images/Black_Magic.webp
    - lib/assets/images/Bedchamber.webp
    - lib/assets/images/Sugar_and_Spice.webp
    - lib/assets/images/Dark_Chocolate.webp
    - lib/assets/images/Green_Tea_Latte.webp
    - lib/assets/images/Gingerbread_Coffee.webp
    - lib/assets/images/Cappuccino.webp
    - lib/assets/images/Bitter_Heart.webp
    - lib/assets/images/Honey_Milk.webp
    - lib/assets/images/Jahe_Tubruk.webp
    - lib/assets/images/Gala_Had.webp
    - lib/assets/images/Midsummer_Nights_Dream.webp
    - lib/assets/images/Caffe_Latte.webp
    - lib/assets/images/Teh_Tarik.webp
    - lib/assets/images/Chocobee_Miruku.webp
    - lib/assets/images/Masala_Chai.webp
    - lib/assets/images/Russian_Tea.webp
    - lib/assets/images/Marrakech.webp
    - lib/assets/images/Black_Lemon.webp
    - lib/assets/images/Milky_Way.webp
    - lib/assets/images/Spanish_Sahara.webp
    - lib/assets/images/WIKICTLOGO-02.webp # Directory for images (logo, character images, etc.)

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
